set(_CATKIN_CURRENT_PACKAGE "controller")
set(controller_VERSION "0.0.0")
set(controller_MAINTAINER "poojith <poojith@todo.todo>")
set(controller_PACKAGE_FORMAT "2")
set(controller_BUILD_DEPENDS "message_generation" "geometry_msgs" "mavros_msgs" "std_msgs" "mavros" "rospy")
set(controller_BUILD_EXPORT_DEPENDS "mavros" "rospy")
set(controller_BUILDTOOL_DEPENDS "catkin")
set(controller_BUILDTOOL_EXPORT_DEPENDS )
set(controller_EXEC_DEPENDS "mavros" "rospy" "message_runtime" "geometry_msgs" "std_msgs" "mavros_msgs")
set(controller_RUN_DEPENDS "mavros" "rospy" "message_runtime" "geometry_msgs" "std_msgs" "mavros_msgs")
set(controller_TEST_DEPENDS )
set(controller_DOC_DEPENDS )
set(controller_URL_WEBSITE "")
set(controller_URL_BUGTRACKER "")
set(controller_URL_REPOSITORY "")
set(controller_DEPRECATED "")