set(_CATKIN_CURRENT_PACKAGE "first_example")
set(first_example_VERSION "0.0.0")
set(first_example_MAINTAINER "poojith <poojith@todo.todo>")
set(first_example_PACKAGE_FORMAT "2")
set(first_example_BUILD_DEPENDS "mavros" "roscpp")
set(first_example_BUILD_EXPORT_DEPENDS "mavros" "roscpp")
set(first_example_BUILDTOOL_DEPENDS "catkin")
set(first_example_BUILDTOOL_EXPORT_DEPENDS )
set(first_example_EXEC_DEPENDS "mavros" "roscpp")
set(first_example_RUN_DEPENDS "mavros" "roscpp")
set(first_example_TEST_DEPENDS )
set(first_example_DOC_DEPENDS )
set(first_example_URL_WEBSITE "")
set(first_example_URL_BUGTRACKER "")
set(first_example_URL_REPOSITORY "")
set(first_example_DEPRECATED "")